version: "3.8"

services:
  web:
    container_name: rag-doc-api
    image: ${DOCKER_IMAGE}
    # build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env

  redis:
    container_name: rag-doc-redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery:
    container_name: rag-doc-celery
    image: ${DOCKER_IMAGE}
    # build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis 
    env_file:
      - .env

    