version: "3.8"

services:
  web:
    container_name: rag-doc-api
    image: rag-doc-api:latest
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
  
  db:
    container_name: rag-doc-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: rag-doc-redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery:
    container_name: rag-doc-celery
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - db
      - redis 
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
  

    