# Generated by Django 5.2.4 on 2025-08-01 17:54

import core.chat.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chat', '0002_remove_session_user_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.chat.models.document.user_session_document_path),
        ),
    ]
