name: RAG-Doc-Chat CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Pytest Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"
            
    env:
      DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
      DEBUG: "TRUE"
      DJANGO_SECRET_KEY: testing-secret-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run migrations
        run: |
          python manage.py migrate
        
      - name: Run tests with Pytest
        run: |
          pytest
